# Generated by Django 4.0.3 on 2022-03-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=1, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('hours', models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('aadhar_card_photo', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo_url', models.CharField(max_length=200, null=True)),
                ('aadhar_number', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('address_line1', models.CharField(max_length=200, null=True)),
                ('address_line2', models.CharField(max_length=200, null=True)),
                ('address_line3', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Contractor', 'Contractor'), ('Owner', 'Owner')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Contractor', 'Contractor'), ('Owner', 'Owner')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Location', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wid', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('aadhar_card_photo', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo_url', models.CharField(max_length=200, null=True)),
                ('aadhar_number', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('address_line1', models.CharField(max_length=200, null=True)),
                ('address_line2', models.CharField(max_length=200, null=True)),
                ('address_line3', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Contractor', 'Contractor'), ('Owner', 'Owner')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WOSMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=0, null=True)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.contractor')),
                ('oid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.owner')),
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.site')),
                ('wid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.worker')),
            ],
        ),
    ]
