# Generated by Django 4.0.3 on 2022-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='mob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='pwd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='mob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='pwd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='mob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='pwd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
