# Generated by Django 4.0.3 on 2022-03-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct_user', '0002_contractor_mob_contractor_pwd_owner_mob_owner_pwd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csid', models.CharField(max_length=200)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.contractor')),
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construct_user.site')),
            ],
        ),
    ]
