# Generated by Django 4.0.3 on 2022-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_user', '0003_contractorsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.CharField(max_length=200, null=True)),
                ('photo_url', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='cid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractorsite',
            name='csid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='oid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
