# Generated by Django 4.0.3 on 2022-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_user', '0005_alter_contractorsite_cid_alter_contractorsite_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosmap',
            name='cid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wosmap',
            name='oid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wosmap',
            name='sid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wosmap',
            name='wid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
