# Generated by Django 4.0.3 on 2022-03-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_user', '0006_alter_wosmap_cid_alter_wosmap_oid_alter_wosmap_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety_violation',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
